use std::path::Path;

fn main() {
    let crate_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("generator lives under crate_root/api/generator");
    let package_name = crate_root
        .file_name()
        .expect("crate root has a directory name")
        .to_string_lossy();

    let rustdoc_json = rustdoc_json::Builder::default()
        .toolchain(public_api::MINIMUM_NIGHTLY_RUST_VERSION)
        .manifest_path(crate_root.join("Cargo.toml"))
        .build()
        .expect("build rustdoc JSON");

    let public_api = public_api::Builder::from_rustdoc_json(rustdoc_json)
        .omit_blanket_impls(true)
        .omit_auto_trait_impls(true)
        .omit_auto_derived_impls(true)
        .build()
        .expect("derive public API");

    let mut output = String::new();
    output.push_str("# ");
    output.push_str(&package_name);
    output.push_str(" public API\n");
    output.push_str("# generated by Surgeist public API artifact tooling\n");

    let missing_item_ids = public_api
        .missing_item_ids()
        .map(u32::to_string)
        .collect::<Vec<_>>()
        .join(", ");
    if !missing_item_ids.is_empty() {
        output.push_str("# missing rustdoc item IDs: ");
        output.push_str(&missing_item_ids);
        output.push('\n');
    }

    output.push('\n');
    output.push_str(&public_api.to_string());

    let artifact = crate_root.join("api/public-api.txt");
    std::fs::write(&artifact, output).expect("write public API artifact");
    println!("wrote {}", artifact.display());
}
